### ISSUE TITLE
NCBI folder have no reference genome

### ISSUE THREAD

**Issue by homopolymer** [alexandrutomescu/metaflow#1]
Hi, where could I find the sequences for the bacteria listed in the NCBI_reference txt file?

**Comment by Sobih** [comment]
Hi, 
The Bacteria reference genomes can be downloaded from NCBI FTP server ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq/Bacteria/ . The file all.fna.tar.gz contains all the sequences. In case BLAST is to be used to alignment, a BLAST database should be created from the sequence files.

**Comment by homopolymer** [comment]
Thanks for your replay.  I have downloaded and unpacked the gz file all.fna.tar.gz. The unpacked directory contains separate FASTA files for bacteria. Next, should I run makeblastdb separately for each bacteria, or merge those separate files into one and then build the Blast index?

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by homopolymer** [comment]
It did not work. I guess there are more hidden information about genome preparation. Could you provide the genome database used in metaflow or a runnable script or tutorial about genome database preparation? Here are errors:

blastn -db /data/fzeng/Genome/NCBI_Bacteria/ncbi_bacteria.fna -outfmt 6 -out mock_62genera_0.01.blast -query mock_62genera_0.01.fasta

convert blast results to graph

Paramters: Blast_File NCBI_Genome_File Average_Read_Length Sequence_Machine
                1-Blast_File: Blast output file. The format must be the tablular format generated by running Blastn with parameter [-outfmt 6]
                2-NCBI_Genome_File: A file contains the species names and length in the NCBI database. The default file path is:- . If a new NCBI database is used, the script ??? can be used for extracting the species names and length.
                3-Average_Read_Length: The average read length of the reads in the sample. 
                4-Sequence_Machine: 0 for Illumena, 1 for 454 Pyrosequencing. If any other sequencer used 0 can be used as default.
['/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py', 'mock_62genera_0.01.blast', '/home/fzeng/Tool/MetagenomeTools/metaflow/NCBI/NCBI_Ref_Genome.txt', '100', '0']
Traceback (most recent call last):
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 223, in <module>
    createLGF(blastFile, ncbiFile, lgfFile)
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 158, in createLGF
    addBlastHits(blastHitList, maxBitScore, refGenomes)
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 146, in addBlastHits
    refGenomes[blastHit.species].addHit(blastHit)
KeyError: 'gi|16271976|ref|NC_000907.1|'
Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by Sobih** [comment]
Hi,
Thank you for trying. We have created a python script for creating the BLAST database from the bacterial sequences. More description will be added soon. You can run the script by calling:
**python Create_Blast_DB.py**
The BLAST database will be generated under the directory **NCBI_DB/**

**Comment by alexandrutomescu** [comment]
Dear Feng,

We have now restructured and simplified the BLAST database creation process. See our new brief tutorial on how to compile a BLAST database from NCBI:
[https://github.com/alexandrutomescu/metaflow/blob/master/TUTORIAL.md](https://github.com/alexandrutomescu/metaflow/blob/master/TUTORIAL.md)

Regarding the specific error you were getting above, it was caused by the fact that the genome name where the read was aligned was **gi|16271976|ref|NC_000907.1|**, which was not in our list of genome names and their lengths. Our new script, callable as 
**python Create_Blast_DB.py**
should now properly format the genome names when creating the BLAST database, and also create the corresponding file with genome names and their lengths.

Thanks again for trying MetaFlow, and please let us know if you encounter problems.

Regards,
Alexandru

**Comment by homopolymer** [comment]
Dear Alexandru

Thanks for the work. I have tried Create_Blast_DB.py to create the NCBI database when it was published first time. Unfortunately, the NCBI DB created by Create_Blast_DB.py has the same dict key problem at the step converting Blast tabular text to LGF. I used samtools faidx to extract genome names and lengths from the Create_Blast_DB.py fna file, and to replaced the NCBI_Genome_List. This did not work. 

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by alexandrutomescu** [comment]
Dear Feng,

We are very sorry for that. Indeed, the first version of Create_Blast_DB.py had quite a few problems. The current version should work correctly (the entire tutorial pipeline should work correctly). 

I cannot pin-point exactly the cause of the error you were getting after your fixes. However, the dict problem from the previous message was due to the genome name from the blast file not appearing exactly in the NCBI_Ref_Genome.txt file. If we can assist, please send us some of your files.

As I said, the current version of Create_Blast_DB.py should work correctly. It also now deals with the following two issues, which are important in creating the database, and were not addressed by the previous version of Create_Blast_DB.py. In addition to extracting the genomes names in the right format, and creating the genome length file, we also needed to eliminate duplicate genome entries from the database (by e.g., selecting the shortest variant), otherwise metaflow will crash. Also, in case of multiple chromosomes (marked in NCBI with "complete sequence"), we need to concatenate them. (Finally, there might still be NCBI entries with both "complete genome" and "complete sequence", of which we still need to keep a single entry.)

Best regards,
Alexandru

**Comment by homopolymer** [comment]
Dear Alexandru

I have re-downloaded the package, but it still failed on our Illumina mock data. As follows are error messages. I tried to send you the Blast file that I used, but failed as the GitHub mail server cannot receive the attachment.

['/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py', 'mock_62genera_0.01.blast', '/data/fzeng/Genome/NCBI_Bacteria/NCBI_DB/NCBI_Ref_Genome.txt', '100', '0']
Constructing the LGF file...
Traceback (most recent call last):
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 224, in <module>
    createLGF(blastFile, ncbiFile, lgfFile)
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 159, in createLGF
    addBlastHits(blastHitList, maxBitScore, refGenomes)
  File "/home/fzeng/Tool/MetagenomeTools/metaflow/BLAST_TO_LGF.py", line 147, in addBlastHits
    refGenomes[blastHit.species].addHit(blastHit)
KeyError: 'Fusobacterium_sp._4'

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University

**Comment by alexandrutomescu** [comment]
Dear Feng,

Thanks again for helping us debug it. I believe I pinpointed this problem.

We were extracting (in both NCBI_Ref_Genome.txt and BLAST_DB.fasta) the genome name 'Fusobacterium_sp._4_8' for that species, but BLAST (either in the database creation step or in the alignment step) was ignoring the final "_8". Hence the Python KeyError.

I have now modified Create_Blast_DB.py to replace any of the third or more occurrences of "_" with "-". Blast seems to preserve such genome names correctly.

Please let me know if this works.

Best,
Alexandru

**Comment by homopolymer** [comment]
Dear Alexandru

Thanks a lot. I will try it.

Best Regards

Feng Zeng, Ph.D
Department of Automation
Xiamen University
